name: testing

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ "1.20.x" ]
        include:
          - go: 1.20.x
            latest: true

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Installing dependencies
        run: go mod download

      - name: Run tests
        run: |
          export PATH=$PATH:/usr/local/go/bin
          go test ./... -v
