name: testing

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ "1.19.x", "1.20.x" ]
        include:
          - go: 1.20.x
            latest: true

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Installing dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v
